In [2]:
import numpy as np

In [144]:
T = [9,1,0,5,0,0,2,9,9,1]

In [170]:
m = np.zeros(len(T)**2).reshape(len(T),len(T))

In [171]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [172]:
roads = [(i,T[i]) for i in range(len(T))]
roads

[(0, 9),
 (1, 1),
 (2, 0),
 (3, 5),
 (4, 0),
 (5, 0),
 (6, 2),
 (7, 9),
 (8, 9),
 (9, 1)]

In [173]:
roads1 = [(i,j) for (j,i) in roads]
roads1

[(9, 0),
 (1, 1),
 (0, 2),
 (5, 3),
 (0, 4),
 (0, 5),
 (2, 6),
 (9, 7),
 (9, 8),
 (1, 9)]

In [174]:
roads1 = roads1 + roads
roads1

[(9, 0),
 (1, 1),
 (0, 2),
 (5, 3),
 (0, 4),
 (0, 5),
 (2, 6),
 (9, 7),
 (9, 8),
 (1, 9),
 (0, 9),
 (1, 1),
 (2, 0),
 (3, 5),
 (4, 0),
 (5, 0),
 (6, 2),
 (7, 9),
 (8, 9),
 (9, 1)]

In [175]:
roads1 = list(set(roads1))

In [176]:
roads1

[(9, 1),
 (9, 8),
 (8, 9),
 (6, 2),
 (4, 0),
 (9, 0),
 (5, 0),
 (0, 4),
 (1, 1),
 (9, 7),
 (2, 6),
 (0, 5),
 (1, 9),
 (3, 5),
 (7, 9),
 (5, 3),
 (2, 0),
 (0, 9),
 (0, 2)]

In [177]:
for (i,j) in roads1:
    if i == j: 
        capital = i
        m[i][j] = 2
    else : m[i][j] = 1
     

In [178]:
display(capital,m)

1

array([[0., 0., 1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 1., 1., 0.]])

In [179]:
d = dict()
d

{}

In [180]:
temp = []
for i in range(len(T)):
    if m[i][capital] == 1:
        m[i][capital] = 2
        temp.append((i,capital))
d[1] = temp
        
d

{1: [(9, 1)]}

In [181]:
m

array([[0., 0., 1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 2., 0., 0., 0., 0., 0., 1., 1., 0.]])

In [182]:
for x in range(2,len(T)):
    temp = []
    for (i,j) in d.get(x-1):
        for y in range(len(T)):
            if m[i][y] == 1:
                m[i][y] = 2
                temp.append((i,y))
            if m[y][j] == 1:
                m[y][j] = 2
                temp.append((y,j))
    d[x] = temp;
        

In [183]:
m

array([[0., 0., 1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 1.],
       [2., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [2., 2., 0., 0., 0., 0., 0., 2., 2., 0.]])

In [184]:
d

{1: [(9, 1)],
 2: [(9, 0), (9, 7), (9, 8)],
 3: [(2, 0), (4, 0), (5, 0)],
 4: [(2, 6), (5, 3)],
 5: [],
 6: [],
 7: [],
 8: [],
 9: []}

In [185]:
output_list = [len(v) for (k,v) in d.items() ]

In [186]:
output_list

[1, 3, 3, 2, 0, 0, 0, 0, 0]